# Generated by Django 2.2 on 2019-07-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yelpscrapy',
            table='review',
        ),
    ]
