# Generated by Django 2.2 on 2019-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_auto_20190715_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.TextField()),
                ('rest_url', models.TextField()),
                ('review_id', models.TextField()),
                ('user_id', models.TextField()),
                ('score', models.TextField()),
                ('date', models.TextField()),
                ('comment', models.TextField()),
                ('useful', models.TextField()),
                ('funny', models.TextField()),
                ('cool', models.TextField()),
                ('label', models.TextField()),
                ('have_pic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.TextField()),
                ('rest_url', models.TextField()),
                ('score', models.TextField()),
                ('total_reviews', models.TextField()),
                ('category', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_avatar', models.TextField()),
                ('user_url', models.TextField()),
                ('user_id', models.TextField()),
                ('user_name', models.TextField()),
                ('data_hovercard_id', models.TextField()),
                ('user_location', models.TextField()),
                ('friends', models.TextField()),
                ('reviews', models.TextField()),
                ('photos', models.TextField()),
                ('countFive', models.TextField()),
                ('countFour', models.TextField()),
                ('countThree', models.TextField()),
                ('countTwo', models.TextField()),
                ('countOne', models.TextField()),
                ('lastDate', models.TextField()),
                ('user_useful', models.TextField()),
                ('user_funny', models.TextField()),
                ('user_cool', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='YelpScrapy',
        ),
    ]
